### ISSUE TITLE
UX: When clicking on inline vote icon second time the inline vote should be hidden

### ISSUE THREAD

**Issue by tiblu** [citizenos/ep_inline_voting#2]
**Reproduce**

* Create inline vote
* Open the existing inline vote by clicking the green icon on the right.
* Click the icon second time
* Nothing happens, the vote modal stays open.

![image](https://user-images.githubusercontent.com/7405383/114598945-29cb8600-9c9b-11eb-866f-68b56fdf9bdb.png)

**Expected**

* Vote modal visibility to be toggled - second click should close it.
* Match the behavior of inline comments.

**Related to:**

* https://github.com/citizenos/ep_inline_voting/issues/1

**Comment by loorm** [comment]
Triage 36. Replicated. Estimated dev time 2 hours. Prioritizing.
